[ROCK-13112] Add virtualizer chain example
Stratio/genai-examples pull request #6
Opened 2024-11-12 15:26 UTC by grios-stratio

2024-11-13 13:52 UTC, pmarin-stratio requested changes
lo dejo aqui escrito que no se nos olvide al mergear: hay que incluir la cobertura de test en el jenkinsfile:
![image](https://github.com/user-attachments/assets/964e4afe-97f2-4975-a745-570033af70d2)

y otra cosa que le he comentado a Marcello: en su dia Diego de las Heras me comento que lo suyo es alinear los examples con la version de genai-core => 0.3.1a0

2024-11-13 13:53 UTC, pmarin-stratio commented on virtualizer-chain-example/pyproject.toml
> +version = "0.1.0a0"
```suggestion
version = "0.3.1a0"
```

2024-11-14 10:12 UTC, pmarin-stratio commented on virtualizer-chain-example/pyproject.toml
> +version = "0.3.1a0"
:+1:

2024-11-14 10:59 UTC, grios-stratio commented on Jenkinsfile
> +                "sonar.python.coverage.reportPaths": "virtualizer-chain-example/pytest-coverage.xml",
done

2024-11-14 11:03 UTC, pmarin-stratio approved these changes
genial

2024-11-14 11:36 UTC, merged